import Background from "./component/background";
import "./style/hero.css";
import "./style/nav.css";
import "./style/pab.css"
import "./style/showreel.css";
import "./style/background.css";
import "./style/homeFooter.css";

export const metadata = {
  title: 'Metama',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Background/>
        {children}
      </body>
    </html>
  )
}
